### ISSUE TITLE
Not able to extract data

### ISSUE THREAD

**Issue by khanhtran192** [ntvuongg/vnese-id-extractor-v2#1]
Cho mình hỏi, có yêu cầu gì về kích thước ảnh không, khi mình up ảnh và extract chỉ hiển thị trạng thái extracting mà không ra kết quả. Mình cảm ơn.

**Comment by ntvuongg** [comment]
Không yêu cầu kích thước ảnh nha bạn. Có khả năng lỗi ở backend rồi bạn thử kiểm tra xem. Repo này mình code và tổ chức còn hơi non tay nên sẽ còn vài case sai.

**Comment by khanhtran192** [comment]
ok ạ, mình cảm ơn
