### ISSUE TITLE
Train model ở CMT

### ISSUE THREAD

**Issue by Thanhdv2007** [ntvuongg/vnese-id-extractor-v2#6]
hiện mình thử ở cccd thì chạy tốt, 
Làm thế nào để có thể đọc cả ở cmt cũ nữa.
Mình cảm ơn

**Comment by ntvuongg** [comment]
Model hiện không được train trên CMT cũ nên sẽ detect không chính xác bạn nhé!

**Comment by Thanhdv2007** [comment]
mình muốn train thêm data thì làm như nào vậy bạn
